package pe.ricardomarcelo.ws.ventas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-24T01:01:26.644Z
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "ClienteWS",
                  wsdlLocation = "http://localhost:8080/ClientesWS-SOAP-JAX-WS/ClienteWS?wsdl",
                  targetNamespace = "http://ricardomarcelo.pe/ws/ventas/")
public class ClienteWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ricardomarcelo.pe/ws/ventas/", "ClienteWS");
    public final static QName ClienteWSPort = new QName("http://ricardomarcelo.pe/ws/ventas/", "ClienteWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ClientesWS-SOAP-JAX-WS/ClienteWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClienteWS_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ClientesWS-SOAP-JAX-WS/ClienteWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClienteWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClienteWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ClienteWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ClienteWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ClienteWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ClienteWS
     */
    @WebEndpoint(name = "ClienteWSPort")
    public ClienteWS getClienteWSPort() {
        return super.getPort(ClienteWSPort, ClienteWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteWS
     */
    @WebEndpoint(name = "ClienteWSPort")
    public ClienteWS getClienteWSPort(WebServiceFeature... features) {
        return super.getPort(ClienteWSPort, ClienteWS.class, features);
    }

}
