package pe.ricardomarcelo.ws.ventas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-22T23:20:53.359Z
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ricardomarcelo.pe/ws/ventas/", name = "ClienteWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteWS {

    @WebMethod
    @Action(input = "http://ricardomarcelo.pe/ws/ventas/ClienteWS/crearRequest", output = "http://ricardomarcelo.pe/ws/ventas/ClienteWS/crearResponse")
    @RequestWrapper(localName = "crear", targetNamespace = "http://ricardomarcelo.pe/ws/ventas/", className = "pe.ricardomarcelo.ws.ventas.Crear")
    @ResponseWrapper(localName = "crearResponse", targetNamespace = "http://ricardomarcelo.pe/ws/ventas/", className = "pe.ricardomarcelo.ws.ventas.CrearResponse")
    @WebResult(name = "resultado", targetNamespace = "")
    public java.lang.String crear(
        @WebParam(name = "cliente", targetNamespace = "")
        pe.ricardomarcelo.ws.ventas.Cliente cliente
    );

    @WebMethod
    @Action(input = "http://ricardomarcelo.pe/ws/ventas/ClienteWS/consultarTodoRequest", output = "http://ricardomarcelo.pe/ws/ventas/ClienteWS/consultarTodoResponse")
    @RequestWrapper(localName = "consultarTodo", targetNamespace = "http://ricardomarcelo.pe/ws/ventas/", className = "pe.ricardomarcelo.ws.ventas.ConsultarTodo")
    @ResponseWrapper(localName = "consultarTodoResponse", targetNamespace = "http://ricardomarcelo.pe/ws/ventas/", className = "pe.ricardomarcelo.ws.ventas.ConsultarTodoResponse")
    @WebResult(name = "cliente", targetNamespace = "")
    public java.util.List<pe.ricardomarcelo.ws.ventas.Cliente> consultarTodo();
}
