//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.22 at 04:45:18 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ricardomarcelo.pe/ws/ventas/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pe.ricardomarcelo.ventas.ws;
